# Generated by Django 3.0.7 on 2022-09-13 18:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10000, null=True)),
                ('image', models.CharField(max_length=20000)),
                ('price', models.CharField(max_length=10000)),
                ('des', models.CharField(max_length=10000, null=True)),
                ('rating', models.CharField(max_length=10000, null=True)),
                ('link', models.CharField(max_length=10000, null=True)),
                ('quantity', models.IntegerField(default=0, null=True)),
                ('date_ordered', models.DateTimeField(auto_now_add=True, null=True)),
                ('complete', models.BooleanField(default=False, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
