# Generated by Django 3.0.7 on 2022-09-13 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appecom', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='image',
            new_name='img',
        ),
    ]
